### ISSUE TITLE
Cannot compile on Raspberry PI

### ISSUE THREAD

**Issue by plop3** [tliff/indi_ardust4#1]
Hello,

I have installed indi-bin and libindi-dev

I can not compile inidi_ardust4 on Banana PI/Raspberry PI:

cmake . OK
make
[ 50%] Building CXX object CMakeFiles/indi_ardust4.dir/ardust4.o
In file included from /root/indi_ardust4/ardust4.cpp:22:0:
/root/indi_ardust4/ardust4.h:67:21: error: conflicting return type specified for ‘virtual IPState ARDUST4::GuideNorth(float)’
     virtual IPState GuideNorth(float ms);

Where is the problem ?

Thanks

**Comment by tliff** [comment]
I dont have a raspberry here but was able to reproduce the problem on an ubuntu 14.04 machine.

It seems your installed libindi is too old. Can you try with a newer version?
