### ISSUE TITLE
Cannot compile Code on raspberry pi 3 B+ with raspbian

### ISSUE THREAD

**Issue by YugnatD** [tliff/indi_ardust4#3]
Hi,
I'm trying to compile your code to use indi.
but i'm getting this error :
pi@raspberrypi:~/Desktop/indi_ardust4-master $ make
Scanning dependencies of target indi_ardust4
[ 33%] Building CXX object CMakeFiles/indi_ardust4.dir/ardust4.o
/home/pi/Desktop/indi_ardust4-master/ardust4.cpp:29:46: error: invalid new-expression of abstract class type ‘ARDUST4’
 std::unique_ptr<ARDUST4> gpGuide(new ARDUST4());
![Error](https://user-images.githubusercontent.com/49752168/56356631-b0971680-61d9-11e9-95c9-977142d9d829.PNG)

Do you have any idea to solve this error ?

Thanks for your work.

**Comment by tliff** [comment]
Seems like an argument type changed.

Can you pull  master and try again?

**Comment by YugnatD** [comment]
what do you mean as "Pull master" ?
sorry I don't understand.
thank you to reply that fast.

**Comment by tliff** [comment]
If you downloaded with git do a `git pull` in the directory.
If you downloaded the zip file simply download it again.

**Comment by YugnatD** [comment]
thank you, it worked, sorry to disturb you for an issue that simple, I don't understand why it has not worked the first time.
Have a gode day.

**Comment by tliff** [comment]
> thank you, it worked, sorry to disturb you for an issue that simple, I don't understand why it has not worked the first time.

I fixed it in the meantime ;)
