### ISSUE TITLE
Proper release 

### ISSUE THREAD

**Issue by pozar87** [tliff/indi_ardust4#4]
Hi!
Thanks for implementing this driver! I'm just about to test it, but to keeps things organized in my file system I've just created an AUR package for Arch-based distributions (see the details at https://aur.archlinux.org/packages/libindi_ardust4/)

The only problem for now is lack of proper github rlease - so I'm forced to download master... Which is not grate :D Can you please release the proper version please?

Best Regards, 
Łukasz

**Comment by tliff** [comment]
Hi Łukasz,

i tagged v0.1 as a release

**Comment by pozar87** [comment]
Perfect! Exactly what I needed :) 
Thanks for a blazingly fast response!
